### ISSUE TITLE
强制更新

### ISSUE THREAD

**Issue by Dooberz** [oureveryday/PikPak_By_Shimily_Keygen#14]
新版本强制更新 无法使用

**Comment by oureveryday** [comment]
请使用最新版
https://github.com/oureveryday/PikPak_By_Shimily_Keygen/releases/tag/v4.3.9

**Comment by Dooberz** [comment]
> 请使用最新版 [`v4.3.9` (release)](https://github.com/oureveryday/PikPak_By_Shimily_Keygen/releases/tag/v4.3.9)

应该是账号别拉黑了 换其他账号可以，强制更新提示让更新到4.3.3 但是用的是最新版。还有问题就是登录激活之后下载还是提示未激活，到该5秒激活失效，应该是有某种验证

**Comment by oureveryday** [comment]
打开原始程序撤销激活，再复制机器码到激活码处即可彻底完成激活

**Comment by oureveryday** [comment]
> > 请使用最新版 [`v4.3.9` (release)](https://github.com/oureveryday/PikPak_By_Shimily_Keygen/releases/tag/v4.3.9)
> 
> 应该是账号别拉黑了 换其他账号可以，强制更新提示让更新到4.3.3 但是用的是最新版。还有问题就是登录激活之后下载还是提示未激活，到该5秒激活失效，应该是有某种验证

如使用中提示需要激活：点击`赞助作者` ->输入任意激活码 -> 点击`立即激活`
