### ISSUE TITLE
Crack don't work

### ISSUE THREAD

**Issue by M3TRI** [oureveryday/PikPak_By_Shimily_Keygen#17]
Activation doesn't work, I get the message "Invalid code"
![Screenshot_11](https://github.com/user-attachments/assets/971215de-0126-48f7-ad1a-8eca1d0c12b8)

**Comment by oureveryday** [comment]
Please download [latest version](https://github.com/oureveryday/PikPak_By_Shimily_Keygen/releases/download/v4.3.9/PikPak.Desktop_crk.exe) and input random code such as `123`
