### ISSUE TITLE
4.0.0 client can't activate

### ISSUE THREAD

**Issue by elsword50716** [oureveryday/PikPak_By_Shimily_Keygen#2]
As title said. The author update the app, old keygen fails.

**Comment by Shimily-3** [comment]
> As title said. The author update the app, old keygen fails.
@elsword50716 个人开发者不易，有能力建议赞助下作者，一杯奶茶钱而已，直接永久使用，如果都想着破解白嫖那作者也没有动力继续更新和维护下去了！
