### ISSUE TITLE
最新版激活码失效

### ISSUE THREAD

**Issue by wowdd1** [oureveryday/PikPak_By_Shimily_Keygen#3]
https://www.wolai.com/shimily/9e3LM4yHhhFdxjiWo8gqsm

**Comment by Shimily-3** [comment]
我是PikPak第三方电脑版的开发者，如果你确实有经济困难，无法赞助作者一杯奶茶的钱可以联系我，我免费赠送你一个激活码，但是希望不要等着大佬破解，如果个人软件生态被破坏了，按谁都没办法继续坚持为何和开发这个软件

**Comment by 2477945104** [comment]
> 我是PikPak第三方电脑版的开发者，如果你确实有经济困难，无法赞助作者一杯奶茶的钱可以联系我，我免费赠送你一个激活码，但是希望不要等着大佬破解，如果个人软件生态被破坏了，谁都没办法继续坚持更新维护和开发这个软件

哥 给我整个 我微信就剩几百吃不起饭了

**Comment by chxin579** [comment]
作者换加密方式了，激活码只能找作者，或者等大佬给程序打补丁，不过版本可能跟不上，以前的旧版也不是不能用，只要官方没改api。

**Comment by RSDCFGVHBJNKML** [comment]
3.0.3养老了，更新提示和作者自己的广告已经抓包之后用防火墙挡出去了，配合脚本使用非常好

**Comment by gagmeng** [comment]
同求大佬更新KG

**Comment by Shimily-3** [comment]
> 同求大佬更新KG
你可以继续使用3.0版本，作者辛苦开发几个月4.0版本被破解了的话那后面还有啥动力继续更新下去？

**Comment by Rooil** [comment]
就那个邀请机制都让你薅到不少了😀开了会员你就能拿到会员激励了。

**Comment by oureveryday** [comment]
之前没时间，现在看看能不能破

**Comment by oureveryday** [comment]
已更新破解方法，请到releases下载。

**Comment by evilsquizz** [comment]
> 我是PikPak第三方电脑版的开发者，如果你确实有经济困难，无法赞助作者一杯奶茶的钱可以联系我，我免费赠送你一个激活码，但是希望不要等着大佬破解，如果个人软件生态被破坏了，谁都没办法继续坚持更新维护和开发这个软件

if online begging really works，i'll do it rn！

**Comment by Jaimeboo** [comment]
还有码码大佬

**Comment by chxin579** [comment]
@Shimily-3 新版卡死了，就几百个文件看详情卡半天，离线下载也缺少，下载也是动不动卡半天还下载不全，能不能把旧版的登录修复一下，新版还不如旧版好用
