### ISSUE TITLE
关掉软体重开之后就无法使用

### ISSUE THREAD

**Issue by fondplay-neo** [oureveryday/PikPak_By_Shimily_Keygen#5]
只要关闭软体再打开就会提示请支持正版的讯息因而无法使用，
最无奈的是，虽然我有这个软体的正版激活序号，
但是他是和帐号绑一起的，换了帐号 VIP 就没了 囧

**Comment by wowdd1** [comment]
破解已经失效  望更新

**Comment by us90210e** [comment]
以前的key 非常简单，新手也会。4.10 key 新手用 python运行，会有很多问题的。一会缺 cython 一会缺 distutils 好不容易解决了，不报错了，却没有破解提示。可能还是python环境没搭建好。pycharm装了N次。python也换了N个版本。

**Comment by jacksonyoyo** [comment]
4.10 已失效

**Comment by us90210e** [comment]
最新版是4.21了  旧的4.x系列强制无法使用，只能用新版。这天天升级，估计也天天换算法。2023.12.21

**Comment by us90210e** [comment]
安装的是最新版本Python3.12  安装时能勾上的都勾上了，比如path

Python keygen.py           #早些的3.0版本 By_Shimily   适用。运行正常。
Python setup.py              #4.1版本By_Shimily  适用。有很多问题。

#ModuleNotFoundError: No module named 'distutils'   
# 4.1版本。如果提示上面这个错误。那么运行下面这行。

pip install setuptools    #安装这个，应该成功解决 distutils 错误。

Python setup.py    
# 继续运行上面这行。应该提示错误如下：
# ModuleNotFoundError: No module named 'Cython'

#继续安装下面这行。
pip install Cython
#提示应该包括下面2行：
#Installing collected packages: Cython
#Successfully installed Cython-3.0.7

#继续安装下面这行。
Python setup.py      
#可能出现下面提示：
Python setup.py
Compiling encrypt.py because it changed.


#继续执行下面命令 
Python  encrypt.py
#如果是3.0版本。会提示让你输入机器码了。
#4.1不报错。只是弹回没输入这行时的提示符状态，大致如下：
#PikPak_By_Shimily_Keygen-4.1.0\encrypt>
#PS:  by_shimily已经升级为4.21版本，估计算法也换了。
#2023.12.21   顺便学习了python

**Comment by ericshug** [comment]
3.0系列  3.x的Keygen 在哪裡?

**Comment by ubabou** [comment]
>>> import encrypt
>>>
>>> # 새로운 키를 얻고자 하는 사용자 ID
>>> user_id = "11DD05D0CD7837021FE9A161376BBD61B2ED9F76"
>>>
>>> # 해당 사용자 ID에 대한 새로운 비밀 키 얻기
>>> new_secret_key = encrypt.get_secret_key(user_id)
>>>
>>> print(new_secret_key)  # 새로운 비밀 키 출력
软件已破解，输入任意的激活码即可激活！
>>> user_id = "11DD05D0CD7837021FE9A161376BBD61B2ED9F76"
>>> import encrypt
>>> help(encrypt)
Help on module encrypt:

NAME
    encrypt

FUNCTIONS
    checkLicense(secret_key, license)
        This function needs to implement the ability to check a license with the given secret_key.

    get_machine_code(user_id)
        This function needs to implement the ability to retrieve a machine code based on user_id.

    get_secret_key(user_id)
        This function needs to implement the ability to generate a secret key based on user_id.

    hmac_md5(s, key='lovePikPak#520_Shimily')
        This function needs to implement the ability to generate a HMAC MD5 hash given input s and a key.

DATA
    __test__ = {}
    public_key = 96466545293696133835704838363233960342
    public_key_data = b'-----BEGIN RSA PUBLIC KEY-----\\nMEgCQQC4L915VO......

FILE
    c:\users\ubabo\appdata\local\programs\python\python39\lib\site-packages\encrypt.cp39-win_amd64.pyd


>>> public_key 11DD05D0CD7837021FE9A161376BBD61B2ED9F76
  File "<stdin>", line 1
    public_key 11DD05D0CD7837021FE9A161376BBD61B2ED9F76
               ^
SyntaxError: invalid syntax
>>>

What should I do next?

**Comment by oureveryday** [comment]
4.3 已修复，使用方法见releases

**Comment by ubabou** [comment]
> 4.3 已修复，使用方法见releases

Run PikPak Desktop_Cracked.exe, log into your account, and enter the registration code to activate it.
After a program crash, "PikPak Desktop.exe" allows you to use the activated features normally.
I told you, but I don't know how to get a registration code
How do I get it?
Is it a system that enters my key and receives it like before? It's hard to understand ㅜㅜ
Please help me

**Comment by oureveryday** [comment]
> > 4.3 已修复，使用方法见releases
> 
> Run PikPak Desktop_Cracked.exe, log into your account, and enter the registration code to activate it. After a program crash, "PikPak Desktop.exe" allows you to use the activated features normally. I told you, but I don't know how to get a registration code How do I get it? Is it a system that enters my key and receives it like before? It's hard to understand ㅜㅜ Please help me

Just input some random characters and click activate.

**Comment by ubabou** [comment]
> > > 4.3 已修复，使用方法见releases
> > 
> > 
> > Run PikPak Desktop_Cracked.exe, log into your account, and enter the registration code to activate it. After a program crash, "PikPak Desktop.exe" allows you to use the activated features normally. I told you, but I don't know how to get a registration code How do I get it? Is it a system that enters my key and receives it like before? It's hard to understand ㅜㅜ Please help me
> 
> Just input some random characters and click activate.

Thank you. I succeeded. Good *-----*

**Comment by ubabou** [comment]
> > > 4.3 사용 방법 릴리스
> > 
> > 
> > PikPak ​​Desktop_Cracked.exe를 실행하고 계정에 로그인한 후 등록 코드를 입력하여 활성화하세요. 프로그램 충돌 후 "PikPak ​​Desktop.exe"를 사용하면 활성화된 기능을 정상적으로 사용할 수 있습니다. 말씀드렸지만 등록코드를 어떻게 받는지 모르겠어요 어떻게 받나요? 예전처럼 내 키를 입력해서 받는 시스템인가요? 이해하기 힘드네요 ㅜㅜ 도와주세요
> 
> 임의의 문자를 입력하고 활성화를 클릭하세요.

There's a problem..
It gets loose quickly, so I can't use it
