### ISSUE TITLE
登录不了咋办

### ISSUE THREAD

**Issue by C0nst4ntine** [oureveryday/PikPak_By_Shimily_Keygen#7]
登录之后就直接转圈圈，啥操作都不能进行

**Comment by oureveryday** [comment]
建议使用Pikpak_desktop.exe登陆后在使用Pikpak_desktop_crack.exe激活。

**Comment by oureveryday** [comment]
建议使用Pikpak_desktop.exe登陆后在使用Pikpak_desktop_crack.exe激活。

**Comment by oureveryday** [comment]
建议使用Pikpak_desktop.exe登陆后在使用Pikpak_desktop_crack.exe激活。

**Comment by C0nst4ntine** [comment]
> 建议使用Pikpak_desktop.exe登陆后在使用Pikpak_desktop_crack.exe激活。

还是没有用

**Comment by oureveryday** [comment]
已修复更新4.3.9
